### ISSUE TITLE
[Report] Vaccination coverage

### ISSUE THREAD

**Issue by sachsk** [avniproject/calcutta-kids#135]
## Context 
As we are unable to add this charts in the dashboard due to metabase filter limitations we have decided to create a separate report for each graph with their linelist

## Reports
Filters: Date filter on the due date
- [x] Vaccination  coverage area wise (Bar graph)

- Numerator: Count of unique children whose - all the vaccine's which have due date in the year filter are completed ie. have completion date in the selected time-range
- Denominator: Count of unique children who has any one vaccine's due date in the selected time-range
---
- [x] Vaccination  coverage  (Pie Chart) 
- Numerator: Count of unique children whose - all the vaccine's which have due date in the year filter are completed ie. have completion date in the selected time-range
- Denominator: Count of unique children who has any one vaccine's due date in the selected time-range
---

- [x] Vaccination  coverage  monthly trend (bar graph)
- **Logic :** Month wise percentage of vaccination coverage in the current year(selected duration in the date filter) ie. group the following by Month of due date
- Numerator: Count of unique children whose - all the vaccine's which have due date in the year filter are completed ie. have completion date in the selected time-range
- Denominator: Count of unique children who has any one vaccine's due date in the selected time-range

---
- [x] Vaccination complete linelist
- **Logic :** List of unique children whose - all the vaccine's which have due date in the year filter are completed ie. have completion date in the selected time-range
- Data to show: show all individual, address and vaccination related data

***

- [x] Vaccination due linelist
- **Logic :** list of unique children who has any one vaccine's due date in the selected time-range
- Data to show: show all individual, address and vaccination related data

**Sample image**

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1QQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42003c4fed75ee3e302ef2b663fbbed64c2a7247/Screenshot%202024-02-27%20at%208.40.54%E2%80%AFAM.png" alt="Screenshot 2024-02-27 at 8.40.54 AM.png" />

**Comment by vedfordev** [comment]
@sachsk for first 3 logic is same as previous.

**Comment by sachsk** [comment]
@vedfordev 

- [ ] Is voided check is missing 
- [ ] Make date filter mandatory
- [ ] count is miss matching
