### ISSUE TITLE
[Report] Preterm Birth Rate

### ISSUE THREAD

**Issue by sachsk** [avniproject/calcutta-kids#136]
## Context
Clint needs a report where they can see the preterm rate in the CK and non-CK mother

## Report

**Filter :** Date range on the delivery date or the date of birth

- [x] Preterm Birth Rate CK and non-CK (bar graph)

- Numerator : Count of mother whose child is born as preterm
- Denominator : Count of total mother within selected time range (date of delivery)
- **Logic :** 
```
- In child prgram-->birth form->general(FEG)->Gestational age category at birth. from here we can decide whether the child is preterm or not.
-  if the child is preterm or very preterm then mother of that child is counted as the preterm mother
- Also from child enrolment you can find out whether mother is associated with CK or not
```

- [x] Linelist of mother whose child is born as preterm
- [x] Linelist of mother within selected time range

**Comment by BEULAHEVANJALIN** [comment]
Query: https://gist.github.com/BEULAHEVANJALIN/7e94f9bc5844a624505a659b9e619a32
