### ISSUE TITLE
Move report to ETL

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/calcutta-kids#150]
Link to the ticket - https://avni.freshdesk.com/a/tickets/3677

- [x] [Monthly Report - Normal children](https://reporting.avniproject.org/question/603-monthly-report-normal-children)
- [x] After migrating, make sure the filters are working as expected.

**Comment by BEULAHEVANJALIN** [comment]
Old report: https://reporting.avniproject.org/question/603-monthly-report-normal-children
New report: https://reporting.avniproject.org/question/3130-monthly-report-normal-children-under-testing
