### ISSUE TITLE
Move report to ETL - SES survery due list

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/calcutta-kids#153]
Link to the ticket - https://avni.freshdesk.com/a/tickets/3666

Link to the report - https://reporting.avniproject.org/question/182-ses-survey-due-list?in_current_year=past1years

- [x] Move report to ETL
- [x] Test data with filters

**Comment by BEULAHEVANJALIN** [comment]
Old report: https://reporting.avniproject.org/question/182-ses-survey-due-list
New report: https://reporting.avniproject.org/question/3145-ses-survey-due-list-do-not-use-under-testing
