### ISSUE TITLE
CK 2024: Metabase Dashboard: Child Nutrition Pie chart

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#166]
In the[ CK Dashboard](https://reporting.avniproject.org/dashboard/222-dashboard-reports?date_filter=thisyear), under Child Program; Child Nutrition Pie chart, we need to separate the current Child Nutrition Pie chart into four separate Pie Charts and also create the line list for them

- [ ] Normal: + or 0 : Pie Char + Line list ([ it is already done ](https://reporting.avniproject.org/question#eyJuYW1lIjoiQ2hpbGQgTnV0cml0aW9uIFBpZSBjaGFydCAiLCJkZXNjcmlwdGlvbiI6bnVsbCwiZGF0YXNldF9xdWVyeSI6eyJkYXRhYmFzZSI6MTcsInF1ZXJ5Ijp7ImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsImNoaWxkX3N0YXR1cyIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIk5vcm1hbCBDaGlsZCJdLFsidGltZS1pbnRlcnZhbCIsWyJmaWVsZCIsImVuY291bnRlcl9kYXRlX3RpbWUiLHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dLCJjdXJyZW50IiwieWVhciJdXSwic291cmNlLXRhYmxlIjoiY2FyZF9fMjkwMCJ9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=))
- [ ] Mild if weight for age is =-1 to =<-2: Pie Char + Line list 
- [ ] Moderator if weight for age is = -2.1 to =<-2.9: Pie Char + Line list 
- [ ] Severe if weight for age is = -3 and below (eg -4, -5 etc): Pie Char + Line list 
- [ ] [Logic for the pie chart:](https://docs.google.com/spreadsheets/d/1AzSqMT0ksZAes29qxpWAINOIDE3mrFv3/edit#gid=683740308&range=29:29)

**Comment by Dinesh2019** [comment]
- [ ] For Normal data displays till -2.0 values but it should display between + or 0 
- [ ] for Severe line list is missing

**Comment by sachsk** [comment]
@Dinesh2019 @AnjaliBhagabati The logic for 'mild' has been updated to range from less than 0 to -2.

**Comment by Dinesh2019** [comment]
@sachsk still norma display values till -2

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk5RQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52bb4ecb4f8bfcf9e27d1798125ccf9f921a7e30/Screenshot%202024-04-11%20at%2012.21.36%E2%80%AFPM.png" alt="Screenshot 2024-04-11 at 12.21.36 PM.png" />

**Comment by Dinesh2019** [comment]
@sachsk Normal: + or 0 : Pie Char + Line list but it shows value till -2
