### ISSUE TITLE
CK 2024: Metabase Dashboard: Stack bar chart for Undernutrition Child

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#167]
In the [CK Dashboard](https://reporting.avniproject.org/dashboard/222-dashboard-reports?date_filter=) under the Child Program section, Area wise bar graph, we need to create a **Stack bar chart** and **linelist** for Undernutrition Child Bar Graph showing  Normal, Mild, Moderate and Severe indicator

- [x] Normal upto  Z-Score  = upto 0 
- [x] Mild Z-Score from =-1 to  =<-2 
- [x] Moderate  Z-Score from =-2.1 to =< -2.9 
- [x] Severe  Z-Score from =-3  below (eg -4, -5 etc)

**Comment by Dinesh2019** [comment]
- [ ] Showing all the line list instead of displaying a particular line list for eg: if we select the mid line list it displaying all the line list from normal to severe

**Comment by sachsk** [comment]
@Dinesh2019 fixed

**Comment by Dinesh2019** [comment]
@sachsk Normal upto Z-Score = upto 0 but it shows till -2 values
