### ISSUE TITLE
Calcutta kids rule migration from Github to App Designer: Child Program

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#215]
**Do this in CK UAT First**

- [x] Child Enrolment 
- [x] Child Exit

**Comment by nupoorkhandelwal** [comment]
- [ ] Birth Form
- [ ] Anthropometry Assessment
- [ ] Child PNC
- [ ] Home Visit
- [ ] PNC Doctor Checkup

**Comment by adamsanadi6** [comment]
@kameshbhariya As discussed in the standup, I moved this card to hold.

**Comment by adamsanadi6** [comment]
As talked about with Sachin The checklist rule is not complete because it already exists.
