### ISSUE TITLE
Calcutta kids rule migration from Github to App Designer: Mother Program

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#216]
**Do this in CK UAT First**

- [x] 	CK Mother Enrolment
- [x] Mother Exit

**Comment by vedfordev** [comment]
@AnjaliBhagabati / @sachsk / @Dinesh2019    
find below

## Mother Exit Form
1. Unable to find any form in ck repo
2. As per my understanding I added skip logic same as prod in prerelease

## CK Mother Enrolment
1. Nothing change. As I see already rules are available.
 
**question :** Check in prerelease there is no program eligibility rule. So, I think we have to provide that. Currenly it is not avialable.

**Comment by vedfordev** [comment]
@pkundu I checked with @petmongrels. exit rules are simple. So app designer rule will work fine.

**Comment by Dinesh2019** [comment]
QA Refrences video : 

[Click here for video](https://drive.google.com/file/d/1hYDUpzCzfGeX9eYExNXpERHATN02bMJE/view?usp=drive_link)
