### ISSUE TITLE
Calcutta kids rule migration from Github to App Designer: Pregnancy Program

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#217]
**Do this in CK UAT First**

- [x] Mother Enrolment
- [x] Mother Exit

**Comment by vedfordev** [comment]
@nupoorkhandelwal you made changes ck mother. Please make changes in mother enrolment

**Comment by Dinesh2019** [comment]
- [ ] The decision rule is not working as expected.

Refer image : 

<img width="366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUUxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a3770fbb05f5b83e0ed4de85ee818dcbcb0e840/Screenshot%202024-08-06%20at%203.11.11%E2%80%AFPM.png" alt="Screenshot 2024-08-06 at 3.11.11 PM.png" />

**Comment by vedfordev** [comment]
@Dinesh2019 it is related to mother not pregnancy
