### ISSUE TITLE
Calcutta kids rule migration from Github to App Designer: Individual

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#218]
**Do this in CK UAT First**

- [x] Calcutta Kids Registration Form

**Comment by adamsanadi6** [comment]
It was already completed by other developers.

**Comment by Dinesh2019** [comment]
Reference video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0FEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b10ca657f1834cd920b49eb9ed8954ae0b033c66/My%20Movie.mp4
