### ISSUE TITLE
Calcutta kids rule migration from Github to App Designer: Birth

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/calcutta-kids#219]
Do this in CK UAT First

- [x] Birth Form
- [x] Default Program Encounter Cancellation Form

Note: Default Program Encounter Cancellation Form is being used in multiple encounters.

**Comment by Dinesh2019** [comment]
Decision rule is not behaving as expected 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e396e4048a6c19de9d2796824be070e041232271/Screen%20Recording%202024-07-25%20at%206.56.15%E2%80%AFPM.mov

**Comment by Dinesh2019** [comment]
QA References : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c9304b98ff3357ddf7569a648f4bd60298da326/Screen%20Recording%202024-07-26%20at%205.55.14%E2%80%AFPM.mov
