### ISSUE TITLE
Calcutta kids rule migration from Github to App Designer: ANC Home Visit

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/calcutta-kids#226]
Do this in CK UAT First

- [ ] ANC Home Visit
- [ ] Default Program Encounter Cancellation Form 

Note: Default Program Encounter Cancellation Form is being used for multiple encounters.

**Comment by vedfordev** [comment]
need to debug for 1st sec 3rd question. move card to fresh dev ready.
