### ISSUE TITLE
[CK][Report] Monthly report - Normal/Mild Faltering children  

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#23]
https://openchs.freshdesk.com/a/tickets/259

Ref Doc - https://docs.google.com/spreadsheets/d/1ycvpAzjvDMNkG63NnuJ8Vl4cycsxur9sdebfc61hM1E/edit#gid=455087711
Two reports - 

Monthly report - Normal children
Monthly report - Mild Faltering children

**Comment by vindeolal** [comment]
Monthly report - Normal children : https://reporting.openchs.org/question/603
