### ISSUE TITLE
Calcutta kids rule migration from Github to App Designer: Child PNC

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/calcutta-kids#235]
Do this in CK UAT First

- [x] Child PNC
- [x] Default Program Encounter Cancellation Form 

Note: Default Program Encounter Cancellation Form is being used for multiple encounters.

**Comment by adamsanadi6** [comment]
@Dinesh2019 'Default Program Encounter Cancellation Form' is already done by @manish-sd
