### ISSUE TITLE
[CK Vaccination] Add the new vaccine schedule to enrolment post 1st April 2024

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/calcutta-kids#237]
**Reference scripts** - https://github.com/avniproject/CHETNA-SNEHA/blob/master/newVaccinesInsert.sql

### Tech tasks
For following vaccines we will have to insert these into checklist_item where enrolment dates are post 1st April 2024

- [x] 1.https://docs.google.com/spreadsheets/d/13emmBWo-wo940XimBtTfaCN8IgIANaZ8WypF81AptSA/edit?gid=0#gid=0 - vaccines where marked as 

> Newly Added vaccine?

 as `Yes`
- [x] Run these query for one record and one vaccine first on pre release first for an enrolment post 1st April
- [x] **So before moving vaccine relate changes to pre release, create test enrolments with enrolment date as or after 1st April**

**Comment by adamsanadi6** [comment]
[Script Link](https://github.com/avniproject/calcutta-kids/blob/master/data-fix-sql/Add%20the%20new%20vaccine%20schedule%20to%20enrolment%20post%201st%20April%202024.sql)

**Comment by vedfordev** [comment]
@nupoorkhandelwal @Dinesh2019  Total 67 records enrolments got updated
