### ISSUE TITLE
Calcutta Kids : UAT Feedback: Remove DPT B-1 Vaccine and add dependency condition in few new vaccine

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#245]
- [x] Changes to be first done in CK UAT environment
- [x] Need to remove DPT B-1 vaccine as it is currently not given 
- [x] Dependency condition needs to be added for IPV, PCV, Rota & JE vaccinations which are highlighted in Green in [this sheet](https://docs.google.com/spreadsheets/d/13emmBWo-wo940XimBtTfaCN8IgIANaZ8WypF81AptSA/edit?gid=0#gid=0)

**Note: We will do this fixes and  moved to production after some time when the issue with the Old Vaccination decency condition is resolved and deployed by Product Team** 

---
### Dev Notes:

Vaccination backup on 08 aug 2024 : [File](https://github.com/avniproject/calcutta-kids/blob/master/vaccination_backup.json)

**Comment by himeshr** [comment]
Depends on https://github.com/avniproject/avni-client/issues/1474.
These changes should be deployed only after a majority of Calcutta_kids users have migrated to apk 9.2.0 and later..

**Comment by Dinesh2019** [comment]
we have the status mismatch as per the requirement for JE1 is due date start as 275 days but it is showing as overdue

Refer the video : 

[Click here to watch video](https://drive.google.com/file/d/1hU6QDALcTTxh1Z7HQkzNIZNC_2e7prTn/view?usp=drive_link)

**Comment by vedfordev** [comment]
@Dinesh2019 it took previous month. please test again
