### ISSUE TITLE
{Calcutta Kids} : On Production Feedback: For all Vaccination Reports, column names arrangements showing in proper order

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#249]
- [x] Changes needs to be  made in Production. CK reports are in Metabase
- [ ] For all the Vaccination Reports, the column name arrangement are not showing in the correct format. It should be as below
Area / MYCHI ID / Name of Child / DOB / HH No. / Street / Floor / Contact No. / Alternate contact No./ Mother Name / Due Vaccine name:

**Comment by Dinesh2019** [comment]
We don't have the below column in the old report.

1.HH.No
2.Contact .No 
3.Alternate contact No
4.Mother Name

We have the below column in the old report but not in the requirement 

1.Ind_id
2.Father/Husband

For now ignoring this

**Comment by Dinesh2019** [comment]
- [ ] for Vaccination due linelist [all] row is mismatched Father name is before the Street
