### ISSUE TITLE
CK 2024: Metabase Dashboard: Vaccination Bar Graphs and Pie Chart calculation to be checked 

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#263]
- [ ] CK reports are on Metabase
- [ ] Changes to be made in Production
- [ ] Need to check if the calculation done for the below Bar Graphs and Pie Charts are correct and Matching the [Immunization Due List Vaccination Report](https://reporting.avniproject.org/question/306-immunization-due-list) and  [Monthly Report - Immunizations Eligible and Completed](https://reporting.avniproject.org/question/323-monthly-report-immunizations-eligible-and-completed)
1. [Vaccination Coverage Area Wise (Bar graph)](https://reporting.avniproject.org/question/3055-vaccination-coverage-area-wise-bar-graph)
2. [[Vaccination Coverage Monthly Trend (Bar Graph)](https://reporting.avniproject.org/question/3056-vaccination-coverage-monthly-trend-bar-graph)
3. [[Vaccination Coverage (Pie Chart)](https://reporting.avniproject.org/question/3057-vaccination-coverage-pie-chart)

### Technical differences 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6ef38cc119a0987e500320e0f8517f7cb1d363f/Screenshot%202024-09-27%20at%2011.18.22%20AM.png" alt="Screenshot 2024-09-27 at 11.18.22 AM.png" />

**Comment by nupoorkhandelwal** [comment]
For 1st Bar graph following should be the base query in order to match the result - 
with data as (
    select
        i.id as "IndividualID",
        "Area",
        concat(i.first_name, ' ', i.last_name) as "Full Name",
        ir.afull_name as "Mother's Name",
        ci.item_detail_name as "Vaccination",
        ci.completion_date as "Completion Date",
        case
            when ci.completion_date between {{start_date}}::timestamp and {{end_date}}::timestamp + interval '1' day
            then 'Yes'
            else 'No'
        end as "Completed during time period"
    from checklist_item_checklist_view ci
        join checklist c on ci.checklist_id = c.id
        join program_enrolment_view pe on pe.id = ci.program_enrolment_id
        join public.individual i on i.id = pe.individual_id
        left join individual_name_relationship_view ir on ir.individual_b_id = i.id and ir.a_is_to_b = 'mother'
        join calcutta_kids.address a on i.address_id = a.id
    where ci.item_detail_state = 'Due'
        and c.is_voided = false
        and ci.completion_date is not null
        and ((interval '1' day * COALESCE(ci.expires_after, 36500) + date(ci.base_date)) > {{end_date}}::timestamp)
        and ci.completion_date between {{start_date}}::timestamp and {{end_date}}::timestamp + interval '1' day
)
select count(*) filter (where "Completed during time period" = 'Yes') 
from data

**Comment by AnjaliBhagabati** [comment]
Closing this card as they are correct. We’ve added detailed descriptions within the CK Dashboard 2024 for each indicator to enhance clarity. 
cc: @nupoorkhandelwal @pkundu
