### ISSUE TITLE
[CK][Support] SES Visit is missing

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#31]
ticket - https://avni.freshdesk.com/a/tickets/561

For individual 'Sabnam Khatun', in one Tab there are two SES 
one '24-Dec-2019' and second '13-01-2020' But in the database, there is only one for "13 Jan 2020".

**Comment by sachsk** [comment]
They didn't sync.
In DB for user Sabnam Khatun there is only one program encounter.
