### ISSUE TITLE
[CK][Support] Change in Visit schedule - Abortion followup

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#35]
https://avni.freshdesk.com/a/tickets/608

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 moved changes to staging.

**Comment by garimadosar5** [comment]
QA Notes - 
- If I am cancelling the first follow-up visit, on Save app is crashing.
- If I am doing the first follow-up visit, It schedules the second visit on the same day.
- If I am doing the second followup visit, it is scheduling the third followup visit after 7 days.
- If I am cancelling third followup visit, the app is crashing.

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 

Working on staging. Deploy this on prod.
