### ISSUE TITLE
[CK][Support] Make some fields non-mandatory.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#39]
https://avni.freshdesk.com/a/tickets/761

**Comment by nupoorkhandelwal** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-553fe-2020-09-15-12-32-27.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- form - ANC Doctor Check up, weight is mandatory.
-
