### ISSUE TITLE
[CK][Support] Vaccination schedule is not proper.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#40]
ticket - https://avni.freshdesk.com/a/tickets/1159

Vaccines - For Vitamin 2 and Measles 2, scheduling is the same but showing different in the app.

CK immunisation schedule - https://docs.google.com/spreadsheets/d/17ofzKYuOfCILkcjhUqZhKbG9uxeWlVwyIWXFtJLquP4/edit?usp=drive_web&ouid=115444501370582801094

**Comment by garimadosar5** [comment]
@sachsk What is the status?

**Comment by sachsk** [comment]
Vaccines are scheduling properly as per the immunization schedule.
Not clear from the client side.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- The app is crashing when clicking on the Vaccination button.

**Comment by garimadosar5** [comment]
QA Notes - 
- Scheduling is not proper.
Case - Hari B
 - Measles 2 and 1 are getting scheduled together but Measles 2 should be dependent on 1.
- Also, Measles 1 date is after measles 2.
- Vitamin A5 is scheduled before A1.
- Albendazole 3 is scheduled before 1.
Polio 1 and 3 are scheduled together.
- Pentavalent 1 should be scheduled on 42 days. currently it is more than 2 months.

**Comment by garimadosar5** [comment]
![Screen Shot 2021-05-10 at 12.11.26 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ec153023-1591-4ca7-b86d-a044e9401118)

**Comment by garimadosar5** [comment]
QA Notes -
- Zoheb Khan - dependent vaccines are not getting scheduled.
![Screen Shot 2021-05-10 at 3.47.06 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/b17fca37-2aa7-461d-8057-d794e1a888ce)
