### ISSUE TITLE
New Categories in Doctor Consultation Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/calcutta-kids#43]
Ticket Link:  https://avni.freshdesk.com/a/tickets/1649

Following categories are required for yearly doctor consultations/visits report:

1. Total number of medical consultations provided to pregnant women

2.  Total number of medical consultations provided to children

3.  Total number of medical consultations provided to Mothers

**Comment by sachsk** [comment]
report link : https://reporting.avniproject.org/question/2111-doctor-consultation-yearly-report?year=2021

**Comment by utkarshavni** [comment]
Updated Report here:

https://reporting.avniproject.org/question/2111-doctor-consultation-yearly-report?year=2021

Manually reported total count from client 2962
Metabase count: 2936

Talked to client, manual reporting could have issues in calculation, going ahead with the report.
