### ISSUE TITLE
Dashboard reports (1st - 4th)

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/calcutta-kids#57]
Context: these indicators are for CK management to review the overall performance of the program, for which they needed this dashboard

for logic requirement document confirmed by client refer below link: https://docs.google.com/spreadsheets/d/1AzSqMT0ksZAes29qxpWAINOIDE3mrFv3/edit?usp=drive_link&ouid=111559638012526864678&rtpof=true&sd=true

for dashboard layout please refer: https://drive.google.com/file/d/11byBuuykwd5EWllVRb9cilKrpeV4FV-z/view?usp=drive_link

- Create this dashboard on Metabase
- This dashboard will filter to select Year : for current year figures will be till current date -1, means till yesterday.
- So, no custom date range option is required

- [x] Active Beneficiary Mother count (Numeric count)
- [x] Active beneficiary Child count (Numeric count)
- [x] Provider visit this year to date: Community Health worker (Numeric count)
- [x] Provider visit this year to date: Doctor (Numeric count)

to put a date filter, please refer below sheet to understand the logic with example:
https://docs.google.com/spreadsheets/d/1jzIexlSBhOlh9nBSNIImafY9G9-7SQR7IVqe_6KblOA/edit#gid=0

Dashboard created so far by @Gojo-Taqi 
https://reporting.avniproject.org/dashboard/222-dashboard-reports

- [ ] Moving this card to ready lane as for year filter we can only provide date range options, whoever picks this card can check once if range filter is applied to all the indicators and report is completed or not as per requirement, before giving it to QA.

**Comment by Gojo-Taqi** [comment]
@sachsk @salilsamanvay can I have a reference dashboard for this pls?

**Comment by salilsamanvay** [comment]
@Gojo-Taqi you can check power Dashboard 1

**Comment by Gojo-Taqi** [comment]
Need to pair on the date filter.

**Comment by vedfordev** [comment]
# Notes :

1. checked the query and done small changes.
2. moved query to prerelease.

@sachsk moving card to code review ready. please verify once.

**Comment by vedfordev** [comment]
@salilsamanvay moving card to on hold with following issue.
@sachsk / @nupoorkhandelwal please check below issue.

## Issues :

**Dashboard filter :**
1. There is not default year level filter in metbase [Link](https://discourse.metabase.com/t/dashboard-filter-by-year/20805).

**Comment by salilsamanvay** [comment]
Moving this card to ready lane as for year filter we can only provide date range options, whoever picks this card can check once if range filter is applied to all the indicators and indicators are completed as per requirement, before giving it to QA.

**Comment by vedfordev** [comment]
@sachsk moving card to code review lane please review.

**Comment by sachsk** [comment]
Review  comments:

- Enc completed by CHW and Doctors: why we are excluding the exited enc? it should consider in the count.
-

**Comment by sachsk** [comment]
Review  comments:

- Enc completed by CHW and Doctors: why we are excluding the exited enc? it should consider in the count.
-

**Comment by vedfordev** [comment]
@sachsk 
if you check other column that excluded exited one.

**Comment by vedfordev** [comment]
@sachsk as you suggested removed exit condition.
