### ISSUE TITLE
Dashboard reports 10th 14th

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/calcutta-kids#64]
## Cotext: 
This card is to add indicators to the dashboard which covers child health 

for logic requirement document confirmed by client refer below link: https://docs.google.com/spreadsheets/d/1AzSqMT0ksZAes29qxpWAINOIDE3mrFv3/edit?usp=drive_link&ouid=111559638012526864678&rtpof=true&sd=true

for dashboard layout please refer: https://drive.google.com/file/d/11byBuuykwd5EWllVRb9cilKrpeV4FV-z/view?usp=drive_link

- [x] Under-nutrition rate: percentage of under-nutrition children by area (Bar graph)
- [x] Under-nutrition rate: percentage of under-nutrition children (Pie Chart)
- [x] Under-nutrition rate: percentage of under-nutrition children by month (Bar graph)
- [x] Low birth weight rate: percentage of child reported as low weight, show by CK mother and non CK month along with toal as well (Bar graph)
- [ ] Preterm Birth rate: percentage of child reported as preterm, show by CK mother and non CK month along with toal as well (Bar graph)

above reports are to be added to the below dashboard which is created for CK:
https://reporting.avniproject.org/dashboard/222-dashboard-reports

- [ ] Moving this card to ready lane as for year filter we can only provide date range options, whoever picks this card can check once if range filter is applied to all the indicators and report is completed or not as per requirement, before giving it to QA.

**Comment by salilsamanvay** [comment]
we need to understand how still birth data point has to be validated, so that it can be excluded from the reports. as per discussion with Sachin he has to check some old version to understand the logic for this.

**Comment by vedfordev** [comment]
@salilsamanvay moving card to on hold with following issue.
@sachsk / @nupoorkhandelwal please check below issue.

## Issues :

**Under-nutrition rate: percentage of under-nutrition children :**
1. as mentioned in sheet we have to take latest encounter but we can't pass dashboard filter to cte because dashboard filter only applied to final query.

**Comment by salilsamanvay** [comment]
Moving this card to ready lane as for year filter we can only provide date range options, whoever picks this card can check once if range filter is applied to all the indicators and report is completed or not as per requirement, before giving it to QA.

**Comment by vedfordev** [comment]
@vaijayanthisundaram can you take a look at this card

**Comment by AnjaliBhagabati** [comment]
@sachsk can you check on this. @vedfordev is having issue applying the filter

**Comment by vedfordev** [comment]
@sachsk As discussed last point of preterm is not clear. moving card to code review ready.
