### ISSUE TITLE
Dashboard line listing report (4 reports)

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/calcutta-kids#65]
Context: Calcutta Kids has asked us to create a dashboard along with that they want us to provide actionable line list reports as well which are linked to summary reports, like when we show the number of child who are fully vaccinated then line which is connected to that is beneficiary missing routine vaccinations, they will use the line list report to get the children vaccinated and once that data is updated in avni indicator of Vaccinated child will increase. similarly all the 4 line list reports will be used in similar ways.

for logic requirement document confirmed by client refer below link: https://docs.google.com/spreadsheets/d/1AzSqMT0ksZAes29qxpWAINOIDE3mrFv3/edit?usp=drive_link&ouid=111559638012526864678&rtpof=true&sd=true

for dashboard layout please refer: https://drive.google.com/file/d/11byBuuykwd5EWllVRb9cilKrpeV4FV-z/view?usp=drive_link

- [x] Beneficiary missing routine vaccinations (Line listing) 
     - Update report as per req. [Report link](https://reporting.avniproject.org/question/2725-children-missing-routine-vaccinations-linelist)
- [x] Beneficiaries who meet undernutrition criteria (line listing)
liked summary reports is undernutrition rate.  [Report Link](https://reporting.avniproject.org/question/2893-beneficiaries-who-meet-undernutrition-criteria)

- [x] Beneficiaries born with low birth weights (line listing)
     - Update report as per req. [Report link](https://reporting.avniproject.org/question/2726-children-born-with-low-birth-weights)
- [x] Beneficiaries born preterm (line listing)
Linked summary report is Preterm birth rate [Report Link](https://reporting.avniproject.org/question/2941-beneficiaries-born-preterm)

above report are to be added to below dashboard which is created for CK:
https://reporting.avniproject.org/dashboard/222-dashboard-reports

**Comment by Gojo-Taqi** [comment]
@salilsamanvay do these reports have to be made in metabase?

**Comment by Gojo-Taqi** [comment]
@salilsamanvay https://docs.google.com/spreadsheets/d/1AzSqMT0ksZAes29qxpWAINOIDE3mrFv3/edit#gid=1347784638
The logic for some reports seems missing.

**Comment by Gojo-Taqi** [comment]
Link to the reports
- https://reporting.avniproject.org/question/2726-children-born-with-low-birth-weights
- https://reporting.avniproject.org/question/2725-children-missing-routine-vaccinations-linelist

Since we can't add a decision on the ETL tables because this is an old implementation, moving this card to On hold for now. Found out about the issue after pairing with @sachsk

**Comment by vedfordev** [comment]
@salilsamanvay Beneficiaries born preterm requirement is not clear. for other move to code ready review.

**Comment by vedfordev** [comment]
@salilsamanvay moving card to on hold with following issue.
@sachsk / @nupoorkhandelwal please check below issue.

## Issues :

**Beneficiaries born preterm (line listing):**
1. some field are related to child program and some related to mother program. How to establish connection between them ?


**Other :**
1. mentioned that we have to add report in dashboard but I am not able to see in layout file.

**Comment by salilsamanvay** [comment]
@vaijayanthisundaram can you please add your analysis on this card, so that developer can consider your suggestions

**Comment by AnjaliBhagabati** [comment]
@vedfordev I have done the below analysis for your below two queries. Can you see if this logic is going to work?

1. Beneficiaries born preterm (line listing):
some field are related to child program and some related to mother program. How to establish connection between them ?
**Analysis:** We can take the LMP (Last Menstrual Period) from the Pregnancy Enrolment form (https://app.avniproject.org/#/appdesigner/forms/026e2f5c-8670-4e4b-9a54-cb03bbf3093d) and the Date of Delivery from the  Mother Delivery form (from encounter: https://app.avniproject.org/#/appdesigner/forms/cc6a3c6a-c3cc-488d-a46c-d9d538fcc9c2) 
Both are Mother Program. We will get the number of babies born also in the Delivery Form. So in case it is  a twins or more we can capture all the babies born to this mother on this date as Pre-term
Excel Formula: Dateif("start date","end date", "W") 
Preterm: Pre-term: less than 259 days (37 weeks) : Ref link https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5139808/#:~:text=Pre%2Dterm%3A%20less%20than%20259,for%20the%20mother%20and%20baby.


2. Other :

mentioned that we have to add report in dashboard but I am not able to see in layout file.

**Comment by AnjaliBhagabati** [comment]
Beneficiaries born preterm (line listing):
some field are related to child program and some related to mother program. How to establish connection between them ?

@vedfordev As discuss on the call with @sachsk , let's go with Option 2
Option 2: Alternatively we can take this from the Child Birth Form as well as this question is captured there
https://app.avniproject.org/#/appdesigner/forms/901e2f48-2fb8-402b-9073-ee2fac33fce4

Can we take the dates from the Child Birth form https://app.avniproject.org/#/appdesigner/forms/901e2f48-2fb8-402b-9073-ee2fac33fce4

**Comment by AnjaliBhagabati** [comment]
@vedfordev can you put the estimate for this

**Comment by sachsk** [comment]
1. Missing routine vaccination: add voided check also show the address details

**Comment by vedfordev** [comment]
@sachsk @Dinesh2019 Beneficiary missing routine vaccinations (Line listing) made as archive. Because we are providing separate linelist.
