### ISSUE TITLE
Clean up data if any related to Goonj entities

### ISSUE THREAD

**Issue by himeshr** [avniproject/calcutta-kids#67]
## Details
- Clean up transactional data if any related to Goonj entities.
- As part of clean-up we had only voided metadata based on bundle uploaded content but not actually deleted them.
This was done, as we wanted to ensure entities if any had been synced to a client get voided some time later.
- After sometime, a month after July 05 2023, we should perform a clean-up activity to 
- [ ] delete all metadata that was voided
- [ ] delete transactional data related to the voided metadata entries

## Bundle and Sql voiding commands are attached here for future reference.

Bundle -  https://app.zenhub.com/files/134670206/d75cdd1f-9a88-4d0c-906b-de1a2293e80c/download
SQL - https://app.zenhub.com/files/134670206/5c901a99-1a3a-44f7-b238-0387a17e3aaa/download
Log - https://app.zenhub.com/files/134670206/fc7eea73-bd18-4f74-93fa-97ba4682abd9/download

**Comment by BEULAHEVANJALIN** [comment]
[https://app.zenhub.com/files/134670206/d75cdd1f-9a88-4d0c-906b-de1a2293e80c/download](https://app.zenhub.com/files/134670206/d75cdd1f-9a88-4d0c-906b-de1a2293e80c/download)

**Comment by vinayvenu** [comment]
[https://app.zenhub.com/files/134670206/5c901a99-1a3a-44f7-b238-0387a17e3aaa/download](https://app.zenhub.com/files/134670206/5c901a99-1a3a-44f7-b238-0387a17e3aaa/download)
