### ISSUE TITLE
Fix the visit scheduling logic for "Doctor visit followup as home"

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/calcutta-kids#75]
Link to the ticket :- https://avni.freshdesk.com/a/tickets/2850

**Comment by nupoorkhandelwal** [comment]
Under addSchedule we had used strategy "createNew" which was scheduling same encounter type visits irrespective of the already scheduled visit. But since the cause is clear to users now, Chandan has asked to not to make any changes in the visit rule.
