### ISSUE TITLE
Org migration (Remove org 1 dependancy)

### ISSUE THREAD

**Issue by sachsk** [avniproject/calcutta-kids#78]
**Context:** we have to create some report on the ETL and since this Org inherited from org 1 we are not able to edit the inherited forms to add the decision concept in the ETL table. 

**Tech task:**
CK is inherited from org 1 so we have to remove that dependency.
To remove the dependancy please follow the steps provided the below doc.
Refer doc: https://docs.google.com/document/d/1yulRXv-Q1DR2aogYDtxuJzwQFgVfsTOAc5tCVZvnlWI/edit?usp=sharing

- [x] Product team to remove the org 1 dependency on pre-release.
- [ ] Product team to remove the org 1 dependency on production.

**Comment by BEULAHEVANJALIN** [comment]
https://docs.google.com/spreadsheets/d/1flz3J_fWqbvFw3RnX0S4Mtsh-qfZtJRcJbY3KJsKbiY/edit?usp=sharing

**Comment by BEULAHEVANJALIN** [comment]
https://gist.github.com/BEULAHEVANJALIN/68db636330dec5bc4d64dcfb4b94b44c

**Comment by BEULAHEVANJALIN** [comment]
In-progress

**Comment by pkundu** [comment]
waiting on data fix 
https://github.com/avniproject/avni-product/issues/1471
