### ISSUE TITLE
Message rule not working because of multiple concepts have the key value "contact_number:yes" present.

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/calcutta-kids#79]
## Tasks 
- To fix the issue, have only one concept which stores the user's phone/contact number.
- Which ever concept is removed, the respectful data will have to be migrated as well.

**Comment by nupoorkhandelwal** [comment]
select * from (
SELECT  name,jsonb_array_elements(key_values) AS elem
FROM concept) data
WHERE elem->>'key' = 'contact_number'
  AND elem->>'value' = 'yes';
