### ISSUE TITLE
Voided individual getting capture in attendances 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/calcutta-kids#84]
when we click any one  individual in the attendance and come out without saving the data void that all the individuals in the group and again try to complete the individual the selected voided individual is displayed 

Steps to reproduce:
1. Click any group (Balwadi, creches, school going, bridge course)
2. Click on the daily attendance which displays the list of individuals select any one individual
3. Click on the back and come to the group page without saving it 
4. Now go to the member and void all the member
5. again click on the daily attendance you will display the individual that u have selected in Step 2 and also voided in Step 4
Expected result: voided individual should not be displayed 
Actual result: voided individual is displayed

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0F6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad99a5a199a58c286c49e20cd7f0b9ca810c5149/Screen%20Recording%202023-10-13%20at%206.10.20%E2%80%AFPM.mov

**Comment by salilsamanvay** [comment]
@sachsk can you have a look at this card

**Comment by Dinesh2019** [comment]
@salilsamanvay @sachsk Still we can able to see the voided individuals 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGZqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dd529deb0d3e097c61441cfe15f9030c18958e7/Screenshot%202023-11-17%20at%208.26.35%E2%80%AFAM.png

**Comment by Dinesh2019** [comment]
We can still able to see the voided individual 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm56QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acf5efd1dfae5133576e0a12701a58bf0ece3e6f/Screenshot%202023-11-21%20at%202.57.14%E2%80%AFPM.png

**Comment by BEULAHEVANJALIN** [comment]
Data-fix has to be done.

**Comment by Dinesh2019** [comment]
The voided scenario was fixed. Please refer the test execution video 

https://drive.google.com/drive/folders/1l63RAYIW_fRxHNXnXXUUGZyxUGXPn9Uv
