### ISSUE TITLE
[CK Support] Migrate Child Due Visit List to ETL

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/calcutta-kids#89]
## Context

Reference Support ticket - https://avni.freshdesk.com/a/tickets/3271

Currently, this report  - https://reporting.avniproject.org/question/207-child-visit-due-list
is taking longer time to load. In order to improve the performance need to update it to use ETL table available.

## Tech Approach

1. Update the new report to use ETL table and save it with as a new report - [DO NOT USE ETL] Child Visit Due List
2. Couple of columns are not available in ETL table, for now we can put them in comment
3. Add same set of filters
4. Once QA is done, replace the original report with the new report.

**Comment by vedfordev** [comment]
## Notes:
 
#### Report Link
https://reporting.avniproject.org/question/2843-do-not-use-etl-child-visit-due-list

#### Points
@sachsk  Need to conform, we see that in old report we see row related to "Doctor Visit Followup at Home". which is not related to child program. Currently I not included it in new etl report.

**Comment by vinayvenu** [comment]
@sachsk ping

**Comment by vedfordev** [comment]
## Dev Test Scenario :

1. In some data we find out that schedule date is diffrent in old and new report. To check used below query and findout old report has some problem.


```
set role calcutta_kids;

select *
from encounter_type where is_voided = false and name = 'Child Home Visit';
-- 33

select *
from program_encounter where encounter_type_id = 33 and individual_id = 891601 and encounter_date_time isnull ;

select *
from program_enrolment where id = 189979;
```

2. For missing data of individual 1335874, new report doesn't have value. To check that used below query and find out that old report shows visit which program was exited.


```
set role calcutta_kids;

select *
from encounter_type where is_voided = false and name = 'Child Home Visit';
-- 33

select *
from program_encounter where encounter_type_id = 33 and individual_id = 1335874 and encounter_date_time isnull ;


select *
from calcutta_kids.individual_child_child_home_visit where individual_id = 1335874 and encounter_date_time isnull ;

select *
from program_enrolment where individual_id = 1335874;
```

**Comment by vedfordev** [comment]
currently facing issue in Metabase .Raised ticket : https://avni.freshdesk.com/a/tickets/3354

**Comment by vedfordev** [comment]
moved report to prerelease : https://reporting.avniproject.org/question/2867-do-not-use-etl-child-visit-due-list-prerelease

**Comment by nupoorkhandelwal** [comment]
@vedfordev please remove commented code from the sql.

**Comment by vedfordev** [comment]
@nupoorkhandelwal @sachsk  moving card to support ready and unassigned me

1. some part are commented because we have to add decision concept.
2. filter work is decide by tech lead 
3. old report has some problem mentioned some scenario in above card.

**Comment by Dinesh2019** [comment]
- [ ] When we cancel the visit the cancel date is not updated on the cancel row in the report.

**Comment by Gojo-Taqi** [comment]
@Dinesh2019 added A,B,C,D as options in age group filter.

**Comment by Dinesh2019** [comment]
Date filter showing error 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelluQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eff0fe6b03bb799dd65f6ee5a19c5745ee587ea3/Screenshot%202024-02-03%20at%208.55.38%E2%80%AFAM.png" alt="Screenshot 2024-02-03 at 8.55.38 AM.png" />

**Comment by Gojo-Taqi** [comment]
Machi read the error message.
It says the date filter is a required parameter.
Unless you don't give a date, it won't run.

**Comment by Gojo-Taqi** [comment]
I am not able to add an encounter_name filter in this report.
Need to pair on this with someone, to move the card forward.
Hence moving the card in QA failed.

**Comment by Gojo-Taqi** [comment]
After Nupoor's help, the issue has been fixed.
Moving it to QA ready.

**Comment by Dinesh2019** [comment]
Child GMP program is missing in the report

**Comment by Dinesh2019** [comment]
Created the data for visit child pnc but data is not reflected in the metabase report

Individual name : Testdin Feb021201
Screenshot :

**Comment by Gojo-Taqi** [comment]
Since the encounter is completed, the individuals details are not coming in the report.
If the encounter is scheduled and not completed, only those encounters will come in the report.
Moving this back to QA ready.
