### ISSUE TITLE
[CK] [Support] Cancel visits are not getting updated in database.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#9]
Scenario - 
- User cancelled visit (Child GMP) and after that a new visit for next month got scheduled. 
- User synced the data.
- New visit scheduled got updated in the database but cancelled visit has not updated there.
- Now in CHILD DUE REPORT for that child, two CHILD GMP visits are scheduled (22 Aug 19 and 22 Sep 19).

Ticket - 
https://openchs.freshdesk.com/a/tickets/410

**Comment by vinayvenu** [comment]
The specific visits mentioned were edited once again and synced, so the reports should work fine. However, we were unable to find the underlying issue.

**Comment by garimadosar5** [comment]
Marking it as closed as the ticket is marked as resolved.
