### ISSUE TITLE
[ETL migration] CK Growth Faltering report

### ISSUE THREAD

**Issue by sachsk** [avniproject/calcutta-kids#96]
Current report link: https://reporting.avniproject.org/question/198-ck-growth-faltering

## Context
As current reports is using the old view its taking long time to open so we have decided to migrate this report to ETL.

## Tech approach 
Currently we have removed CK dependancy on the prerelease so use the prerelease data source for this report.

BI tool : Metabase
Create a new repo call CK ETL (WIP) in this repo save the report.

**Comment by vedfordev** [comment]
## Dev Notes :

**pre release :** [Link](https://reporting.avniproject.org/question/2869-do-not-use-etl-ck-growth-faltering-prerelease)

### Task done:
1. for adding decision concept done below steps:
   1. find all concept id used in decision
   2. find form id in which use
   3. add it in decision_concept table
2. moved query to etl
